# Generated by Django 3.0.5 on 2020-09-08 14:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('separator', models.CharField(max_length=10)),
                ('columns', djongo.models.fields.JSONField()),
            ],
        ),
    ]
