# Generated by Django 3.0.5 on 2020-09-09 11:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 11, 42, 37, 64865), editable=False),
        ),
        migrations.AlterField(
            model_name='processing',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('ac0891cb-821e-48d8-90dc-30bb50147b2c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 11, 42, 37, 64403), editable=False),
        ),
    ]
